### ISSUE TITLE
class container conflicts with bootsrap.css

### ISSUE THREAD

**Issue by vsajip** [vsajip/sphinx_sizzle_theme#2]
**[Original report](https://bitbucket.org/vinay.sajip/sphinx_sizzle_theme/issue/2) by Indian Sunset (Bitbucket: [idnsunset](https://bitbucket.org/idnsunset), GitHub: [idnsunset](https://github.com/idnsunset)).**

----------------------------------------

RST like

```restructuredtext
.. code-block:: none
   :caption: ...

   ...
```

produces a `div` with class `container`:

```html
<div class="literal-block-wrapper docutils container">
  <div class="code-block-caption"></div>
  <div class="highlight-none notranslate"></div>
</div>
```

which conflicts with the `.container` style settings in `bootstrap.css`. It may increases the width of the element and triggers the horizontal scrollbar.

I managed to fix this by adding

```css
.container.docutils {
  padding: 0;
  margin: 0;
  width: inherit;
  max-width: inherit;
}
.container.docutils:before,
.container.docutils:after {
  display: none;
  clear: none;
}
```

in a custom css file.
